### ISSUE TITLE
Mention larq/zoo more clearly on the frontpage and readme

### ISSUE THREAD

**Issue by lgeiger** [larq/docs#11]
`larq/zoo` is an important part of larq, so we should mention it prominently on the Readme and the front page. Otherwise it can be hard for new users to discover.

**Comment by koenhelwegen** [comment]
New landing page should be up sometime this week, I wouldn't put energy into this until that's done

**Comment by lgeiger** [comment]
https://larq.dev/ links prominently to Larq Zoo and Compute Engine, so I think we can close this.
