### ISSUE TITLE
Implement auto-dark mode

### ISSUE THREAD

**Issue by leonoverweel** [larq/docs#112]
Partially enabled by #111, but we should wait until we can follow the user's OS-level preference (defaulting to light if none is set); see squidfunk/mkdocs-material#1266.

**Comment by lgeiger** [comment]
Looks like [this is now possible in the latest version](https://github.com/squidfunk/mkdocs-material/issues/1266#issuecomment-640211410), though it probably requires some manual tuning of our CSS colour variables.
