### ISSUE TITLE
`BinaryAlexNet function` instead of `BinaryAlexNet`

### ISSUE THREAD

**Issue by koenhelwegen** [larq/docs#118]
The zoo API pages ([literature](https://docs.larq.dev/zoo/api/literature/), [sota](https://docs.larq.dev/zoo/api/sota/)) append the headings with "function". Apart from not being very pretty, this has broken all the links in tables like the ones [here](https://docs.larq.dev/zoo/#available-models). @leonoverweel do you know why the "function" has been added, and can it be removed?

**Comment by leonoverweel** [comment]
The fact that "function" and "class" get appended to headings is a known regression introduced in larq/docs#68 which, in the end, we decided was not blocking for the switch to keras-autodoc. The table links should be an easy fix though; I'll make a PR for that now.

**Comment by lgeiger** [comment]
Let's reopen this since I think it would be less noisy to remove the `function` and `class` statements from the docs as well.

**Comment by leonoverweel** [comment]
I fixed this in keras-team/keras-autodoc#83; it hasn't been released to PyPI yet but once it is this issue will be solved by bumping that requirement (and reverting #120). If we want to do it sooner we can install from the current latest commit on master, but I'd prefer to keep this as a PyPI requirement.

(cc @gabrieldemarmiesse, do you think this warrants a patch release or do you want to wait with that until there are more changes?)

**Comment by gabrieldemarmiesse** [comment]
Let's make a patch release. I'll put it in my todo list.

**Comment by leonoverweel** [comment]
@gabrieldemarmiesse hey, just wanted to bump this. :)

**Comment by gabrieldemarmiesse** [comment]
My apologies. I'm terribly sorry. I'll do it right now.

**Comment by gabrieldemarmiesse** [comment]
Done, sorry for the wait.

**Comment by leonoverweel** [comment]
No worries at all, thanks for doing the release!
