### ISSUE TITLE
Broken menu on chrome for android

### ISSUE THREAD

**Issue by timdebruin** [larq/docs#32]
When going into the third menu down on docs.larq.dev using chrome on my phone (Pixel 2) the menu is broken. Specifically, text from higher level menus is shown as well as (and through) the text of that level. This does not happen with firefox on my phone or chrome on desktop.

Below is a screenshot from going to top level > Compute Engine > Build, with chrome left and firefox right:

![image](https://user-images.githubusercontent.com/10598646/76086167-79755380-5fab-11ea-8d4f-518c8c85df1e.png)

Similar things happen when going into other sub-menus at this level (e.g. Larq -> User Guides).

**Comment by AdamHillier** [comment]
> This does not happen with firefox on my phone or chrome on desktop.

I propose we have a big pop-up banner for people visiting from Android Chrome which says "Works best in Firefox" for a [bit of karma](https://thenextweb.com/dd/2017/11/28/please-build-websites-web-not-just-google-chrome/).

**Comment by lgeiger** [comment]
I can't reproduce this on a Pixel 1 with Android 10 and the latest version of Chrome.

**Comment by timdebruin** [comment]
I guess you need a cooler Pixel than because I'm on the bleeding edge of Chrome and Android obvs.

**Comment by timdebruin** [comment]
Fixed by #59
