### ISSUE TITLE
Add guide for exporting binarized weights

### ISSUE THREAD

**Issue by leonoverweel** [larq/docs#41]
This is much easier now with the quantized variable scope in `larq>=0.9`, and it's a question that gets asked a lot (e.g. larq/larq#360 and larq/larq#406). We should add a guide + code snippet explaining how to do this somewhere in the docs.

**Comment by lgeiger** [comment]
I agree, that would be nice. I have a small example in the API docs, but it would probably be good to add it somewhere more prominently: https://docs.larq.dev/larq/api/context/#quantized_scope

**Comment by timdebruin** [comment]
Implemented in #66
